name: chatbot
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  bubble: ^1.2.1
  dialogflow_flutter: ^1.0.0
  dialog_flowtter: ^0.3.3
  
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/dialog_flow_auth.json
    - assets/bot.png
    - assets/person.png

  uses-material-design: true
