name: chatbot
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.2.1
  http: ^1.1.0
  google_generative_ai: ^0.4.6
  #flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/bot.png
    - assets/person.png
  uses-material-design: true